name: Deploy to WordPress.org

on:
  push:
    tags:
      - '*'

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v3

      - name: Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
